### PR TITLE
fix(java): fix ClassLoader npe in loadOrGenCodecClass

### PR DESCRIPTION
**Pull request by chaokunyang**
fix ClassLoader npe in `loadOrGenCodecClass` mentioned in #1340

### CODE REVIEW

**Review by Maurice-Betzel — COMMENTED** [review]
That was my initial idea as well, get the Fury class loader. But I am still curious why a thread does not have a context class loader. The context class loader is set at the time of the creation of a thread. If not set explicitly, it defaults to the context class loader of the parent thread. So somewhere (JIT?) it gets actively nulled out.
Edit, on second thought, if the parent of the thread was the main application thread having a null class loader pointing to the Java boot class loader, it makes sense to get a null context class loader.
I just have not see that happen before in my career.
(removed part)

**Comment by Maurice-Betzel** [comment]
There is another location having the same problem, after adding the solution here as well all seems up and running.
I observe see a strange phenomenon, if I changed Fury code I had to delete my complete runtime data folder because it was holding a reference to previous Fury code somewhere which I did not find yet.

```
  protected Expression getOrCreateSerializer(Class<?> cls) {
    // Not need to check cls final, take collection writeSameTypeElements as an example.
    // Preconditions.checkArgument(isFinal(cls), cls);
    Reference serializerRef = serializerMap.get(cls);
    if (serializerRef == null) {
      // potential recursive call for seq codec generation is handled in `getSerializerClass`.
      Class<? extends Serializer> serializerClass =
          visitFury(f -> f.getClassResolver().getSerializerClass(cls));
      Preconditions.checkNotNull(serializerClass, "Unsupported for class " + cls);
      ClassLoader beanClassClassLoader =
          beanClass.getClassLoader() == null
              ? Thread.currentThread().getContextClassLoader()
              : beanClass.getClassLoader();
      if (beanClassClassLoader == null) beanClassClassLoader = Fury.class.getClassLoader();
```

**Comment by chaokunyang** [comment]
> There is another location having the same problem, after adding the solution to BaseObjectCodecBuilder as well all seems up and running.
> 
> ```
>   protected Expression getOrCreateSerializer(Class<?> cls) {

Good catch, thanks. I just pushed a fix for it.

**Comment by chaokunyang** [comment]
> That was my initial idea as well, get the Fury class loader. But I am still curious why a thread does not have a context class loader. The context class loader is set at the time of the creation of a thread. If not set explicitly, it defaults 

This breaks my assumption too, thread classloader will be app classloader by default, maybe someone set it to null by accident

**Review by theweipeng — APPROVED** [review]

**Pull request merged**
