### PR TITLE
chore: merge main into 0.5.1

### PR DESCRIPTION
**Pull request by chaokunyang**
## What does this PR do?
Fixes:
1. https://github.com/apache/incubator-fury/issues/1604
2. https://github.com/apache/incubator-fury/issues/1615
3. https://github.com/apache/incubator-fury/issues/1633
4. https://github.com/apache/incubator-fury/issues/1640

And introduce some minor optimizations
## Does this PR introduce any user-facing change?

- [ ] Does this PR introduce any public API change?
- [ ] Does this PR introduce any binary protocol compatibility change?

### CODE REVIEW

**Comment by PragmaTwice** [comment]
Hmmm I have a little question about branching and release management.

It seems a little weird to merge something to a release branch continuously. Maybe we can just create the branch from the dev branch after we decide to release 0.5.1? Or maybe we can maintain a branch named `release-0.5`, and use it to create release tag if there are some inconsistencies between release branch and the dev branch? (e.g. follow the semantic versioning)

**Comment by chaokunyang** [comment]
> Hmmm I have a little question about branching and release management.
> 
> It seems a little weird to merge something to a release branch continuously. Maybe we can just create the branch from the dev branch after we decide to release 0.5.1? Or maybe we can maintain a branch named `release-0.5`, and use it to create release tag (0.5.1, 0.5.2...) if there are some inconsistencies between release branch and the dev branch? (e.g. follow the semantic versioning)

The 0.5.1 has been created from dev branch before, we can't overwrite it. Using cherry-pick is better actually. The dev branch didn't introduce big changes so I just created a PR to merge code from dev branch. 

Currently I create release candidate tag from release branch `release-a.b.c`, for example: create tag 0.5.1-rc2 from branch releases-0.5.1. Creating tag from ``release-a.b` looks to me too. I will do that

**Comment by chaokunyang** [comment]
@PragmaTwice What we do here is like the method you proposed in `create the branch from the dev branch after we decide to release 0.5.1`. But I think we can switch to release branch `a.b` instead of `a.b.c`.

**Comment by PragmaTwice** [comment]
> @PragmaTwice What we do here is like the method you proposed in `create the branch from the dev branch after we decide to release 0.5.1`. But I think we can switch to release branch `a.b` instead of `a.b.c`.

I see. Seems now the release procedure is cancelled so maybe we can just delete the old branch and create a new.

**Comment by chaokunyang** [comment]
> > @PragmaTwice What we do here is like the method you proposed in `create the branch from the dev branch after we decide to release 0.5.1`. But I think we can switch to release branch `a.b` instead of `a.b.c`.
> 
> I see. Seems now the release procedure is cancelled so maybe we can just delete the old branch and create a new.

It's protected branch, we can't delete it

**Comment by PragmaTwice** [comment]
> > > @PragmaTwice What we do here is like the method you proposed in `create the branch from the dev branch after we decide to release 0.5.1`. But I think we can switch to release branch `a.b` instead of `a.b.c`.
> > 
> > 
> > I see. Seems now the release procedure is cancelled so maybe we can just delete the old branch and create a new.
> 
> It's protected branch, we can't delete it

https://github.com/apache/incubator-fury/blob/main/.asf.yaml

seems not protected?

**Pull request closed without merging**
