### PR TITLE
fix(license): add DISCLAIMER and NOTICE for built jars

### PR DESCRIPTION
**Pull request by chaokunyang**
This PR adds DISCLAIMER and NOTICE for built jars to comply with ASF release policy

### CODE REVIEW

**Comment by chaokunyang** [comment]
@tisonkun @pjfanning PJ @carp84 @vesense @theweipeng @PragmaTwice , could you help review whether the fix comply with ASF release policy?

The built jar has contained the license:
image

The janino still exists in META-INF/DEPENDENCIES:
image
But since we added the janino to NOTICE, I think it should be OK? @pjfanning

**Review by theweipeng — APPROVED** [review]
LGTM

**Review by pjfanning — APPROVED** [review]
Lgtm. When we get to the Incubator vote, other PMC members might ask for more changes but this should be alright.

**Comment by chaokunyang** [comment]
> Lgtm. When we get to the Incubator vote, other PMC members might ask for more changes but this should be alright.

OK, I will send a new release vote later

**Pull request merged**
