### PR TITLE
docs: Use perf type when pr has performance impact.

### PR DESCRIPTION
**Pull request by LiangliangSui**
When PR has an impact on Fury performance, it is recommended to use perf type and provide benchmark data in the PR description.

### CODE REVIEW

**Review by chaokunyang — APPROVED** [review]
LGTM, We may need to update our pr template too

**Comment by LiangliangSui** [comment]
> LGTM, We may need to update our pr template too

The pr template already contains [perf type](https://github.com/apache/incubator-fury/blob/main/.github/workflows/pr-lint.yml#L48).

**Comment by chaokunyang** [comment]
I mean a pr template like: https://github.com/apache/arrow/blob/main/.github/pull_request_template.md

**Comment by LiangliangSui** [comment]
Okay, I got it, I will update later.

**Pull request merged**
