### PR TITLE
chore(java): rename MemoryBuffer read/write/put/getType with read/write/put/getTypeNumber 

### PR DESCRIPTION
**Pull request by chaokunyang**
This PR refactor `MemoryBuffer` by:
- Rename all methods in name for unsigned varint/varlong write/read methods from write/readPositiveXXX.
- Rename all methods of get/put/read/writeType to type with number. For example, rename `readInt` to `readInt32`
- Remove rebundant code in `MemoryBuffer`
- Rename unsafe method as `_unsafeXXX`

### CODE REVIEW

**Comment by chaokunyang** [comment]
@theweipeng @PragmaTwice @LiangliangSui Please take a look, this is a breaking API changes

**Comment by chaokunyang** [comment]
@theweipeng @PragmaTwice @LiangliangSui Do we need to change all naming to names like `readInt16/readInt32/readInt64/readVarInt32/readVarInt64/readFloat16/readFloat32/readFloat64`/`writeInt16/writeInt32/...`?

**Comment by chaokunyang** [comment]
There are so many `get/put/read/write` `short/int/long/float/double`, change it all to `int16/32/64`/`float16/32/64` will be a huge change.

One solution is that we can keep old naming intact, and add new names too. i.e. `readInt32/readInt` exists at the same time

**Comment by theweipeng** [comment]
> @theweipeng @PragmaTwice @LiangliangSui Do we need to change all naming to names like `readInt16/readInt32/readInt64/readVarInt32/readVarInt64/readFloat16/readFloat32/readFloat64`/`writeInt16/writeInt32/...`?

I think it is very necessary, as it is good for a clear understanding of the data to be process.

**Comment by theweipeng** [comment]
> There are so many `get/put/read/write` `short/int/long/float/double`, change it all to `int16/32/64`/`float16/32/64` will be a huge change.
> 
> 
> 
> One solution is that we can keep old naming intact, and add new names too. i.e. `readInt32/readInt` exists at the same time

There are all built-in APIs, which  user is unaccessable to it. I don't think we need to keep compatibility.

**Comment by chaokunyang** [comment]
> > There are so many `get/put/read/write` `short/int/long/float/double`, change it all to `int16/32/64`/`float16/32/64` will be a huge change.
> > One solution is that we can keep old naming intact, and add new names too. i.e. `readInt32/readInt` exists at the same time
> 
> There are all built-in APIs, which user is unaccessable to it. I don't think we need to keep compatibility.

Users will use this APi to implement their own serializers. Take this library for an example: https://github.com/tommyettinger/tantrum/blob/main/tantrum-jdkgdxds/src/main/java/com/github/tommyettinger/tantrum/jdkgdxds/helpers/Support.java

**Comment by LiangliangSui** [comment]
> @theweipeng @PragmaTwice @LiangliangSui Do we need to change all naming to names like `readInt16/readInt32/readInt64/readVarInt32/readVarInt64/readFloat16/readFloat32/readFloat64`/`writeInt16/writeInt32/...`?

+1, I also think this is very necessary. It’s a cool thing to normalize the naming of data types in various languages.

**Comment by LiangliangSui** [comment]
> There are so many `get/put/read/write` `short/int/long/float/double`, change it all to `int16/32/64`/`float16/32/64` will be a huge change.
> 
> One solution is that we can keep old naming intact, and add new names too. i.e. `readInt32/readInt` exists at the same time

I prefer not to exist simultaneously, as existing at the same time will lead to more confusion of concepts and bloated code base.

The current PR has modified the common interface in [MemoryBuffer(e.g. writePositiveVarInt -> writeVarUint32)](https://github.com/apache/incubator-fury/pull/1480/files#diff-f321dd2324a9ae0cd5808f0281fd200090a9175830937aa3fb48cf309f7e36a1R1136-R1142), which has had an impact on some custom serializers. Now that this compatibility has been broken, we can complete all the renaming work before releasing pkg under `org.apache.fury`. We won't be able to make such more dangerous modifications in the future.

**Comment by chaokunyang** [comment]
The thing is that java `java.nio.ByteBuffer` use `getInt/getLong/putInt/putLong`. If we use a different name here, it may intruduce confusition to users. `org.apache.arrow.memory.ArrowBuf` also use `setInt/setLong/putInt/putLong`

**Comment by chaokunyang** [comment]
Protobuf does use `int32/int64`, see `com.google.protobuf.CodedInputStream#readRawVarint32()`

**Comment by LiangliangSui** [comment]
> The thing is that java `java.nio.ByteBuffer` use `getInt/getLong/putInt/putLong`. If we use a different name here, it may intruduce confusition to users. `org.apache.arrow.memory.ArrowBuf` also use `setInt/setLong/putInt/putLong`

I still prefer `int32/int64`. We can emphasize the compatibility issues of ByteBuffer in the document. We can ask other members of the community for suggestions.

**Comment by chaokunyang** [comment]
> > The thing is that java `java.nio.ByteBuffer` use `getInt/getLong/putInt/putLong`. If we use a different name here, it may intruduce confusition to users. `org.apache.arrow.memory.ArrowBuf` also use `setInt/setLong/putInt/putLong`
> 
> I still prefer `int32/int64`. We can emphasize the compatibility issues of ByteBuffer in the document. We can ask other members of the community for suggestions.

Seems `int32/64` style is better, I will post this to the dev@fury apache.org for more feedbacks

**Comment by PragmaTwice** [comment]
Actually if it's C++/rust I will recommend to use template/generics instead of put type into function name.

But not sure if it's a good way in Java.

**Review by PragmaTwice — APPROVED** [review]

**Comment by chaokunyang** [comment]
> Actually if it's C++/rust I will recommend to use template/generics instead of put type into function name.
> 
> But not sure if it's a good way in Java.

Java generics it erased, it's not feasible to invoke it using generics to dispatch

**Comment by chaokunyang** [comment]
Hi @tommyettinger, do you have any suggestions? You used `MemoryBuffer` widely inhttps://github.com/tommyettinger/tantrum.

Will it be better if we rename all  `read/write/get/put Int/Long/Float/Double` in methods of `MemoryBuffer` to `read/write/get/put Int32/Int64/Float32/Float64`

**Comment by tommyettinger** [comment]
I have no problem using Float32 and Int64 etc. as the terms, I think they're language-neutral and are almost completely self-explanatory. I imagine anyone writing code that uses MemoryBuffer won't have any problem knowing what Float32 vs Float64 mean. In C, I know `long` has some sort of compiler- and architecture-dependent meaning, and also that there's `long long` (which would not be good to see in a method name in other languages, since it looks like a pair of `long`s). So moving towards the types of numbers that at least C++ seems to encourage, like how it has int64_t, should be a good action.

**Comment by chaokunyang** [comment]
> I have no problem using Float32 and Int64 etc. as the terms, I think they're language-neutral and are almost completely self-explanatory. I imagine anyone writing code that uses MemoryBuffer won't have any problem knowing what Float32 vs Float64 mean. In C, I know `long` has some sort of compiler- and architecture-dependent meaning, and also that there's `long long` (which would not be good to see in a method name in other languages, since it looks like a pair of `long`s). So moving towards the types of numbers that at least C++ seems to encourage, like how it has int64_t, should be a good action.

Hi @tommyettinger , thanks for your reply and suggestion. The type with number looks better to me now. I will udpate this PR to use this name style

**Review by theweipeng — APPROVED** [review]
LGTM

**Pull request merged**
