### PR TITLE
feat(java): remove soft/weak ref values from thread safe fury

### LINKED ISSUE #1632: [java] FuryPooledObjectFactory#classLoaderFuryPooledCache remove softValues
## Is your feature request related to a problem? Please describe.

classLoaderFuryPooledCache with `weakKeys`,`softValues`,`expireAfterAccess` , values removed too frequently. In some case it will create too much fury.

## Describe the solution you'd like

I'd like to remove `softValues` options. even `weakKey` can be removed too, just remain `expireAfterAccess`

### PR DESCRIPTION
**Pull request by chaokunyang**
## What does this PR do?

remove soft/weak ref values from thread safe fury

## Related issues

Closes #1632

## Does this PR introduce any user-facing change?

- [ ] Does this PR introduce any public API change?
- [ ] Does this PR introduce any binary protocol compatibility change?

### CODE REVIEW

**Comment by chaokunyang** [comment]
cc @MrChang0

**Comment by MrChang0** [comment]
great, I thinking about that we can add `classLoaderFuryPooledCache.cleanup()` in `getFury()`, make cache clean more timely.

**Review by LiangliangSui — APPROVED** [review]

**Comment by chaokunyang** [comment]
> cleanup

Could you elaborate more details?  If we cleanup classloader in `getFury`. Fury will be created every time

**Comment by chaokunyang** [comment]
> > cleanup
> 
> Could you elaborate more details? If we cleanup classloader in `getFury`, Fury will be created every time.

**Comment by MrChang0** [comment]
we call `cleanup()` to clean data which is expired or drain key/value reference. because cache will hold on data much more time even data is needed to be clean. so if the cache does't operate frequently enough, we can use `cleanup()`. maybe it can  solve `class leak` question.

**Comment by chaokunyang** [comment]
> we call `cleanup()` to clean data which is expired or drain key/value reference. because cache will hold on data much more time even data is needed to be clean. so if the cache does't operate frequently enough, we can use `cleanup()`. maybe it can solve `class leak` question.

I still don't get it. We cleanup the classloader and associated map in:
```java
  public void clearClassLoader(ClassLoader loader) {
    classLoaderFuryPooledCache.invalidate(loader);
    classLoaderLocal.remove();
  }
```
Could you share some code?

**Comment by MrChang0** [comment]
just like 
```java
  @Test
    public void testCache() throws InterruptedException {
      Cache<String, String> cache = CacheBuilder.newBuilder().expireAfterAccess(Duration.ofSeconds(1)).build();
      cache.put("1", "1");
      cache.put("2", "2");
      Assert.assertEquals(cache.size(), 2);
      Thread.sleep(800);
      cache.getIfPresent("1");
      cache.cleanUp();
      Assert.assertEquals(cache.size(), 2);
      Thread.sleep(800);
      cache.getIfPresent("1");
      Assert.assertEquals(cache.size(), 2);
      Thread.sleep(800);
      cache.getIfPresent("1");
      Assert.assertEquals(cache.size(), 2);
      cache.cleanUp();
      Assert.assertEquals(cache.size(), 1);
  }
```

**Comment by chaokunyang** [comment]
> just like
> 
> ```java
>   @Test
>     public void testCache() throws InterruptedException {
>       Cache<String, String> cache = CacheBuilder.newBuilder().expireAfterAccess(Duration.ofSeconds(1)).build();
>       cache.put("1", "1");
>       cache.put("2", "2");
>       Assert.assertEquals(cache.size(), 2);
>       Thread.sleep(800);
>       cache.getIfPresent("1");
>       cache.cleanUp();
>       Assert.assertEquals(cache.size(), 2);
>       Thread.sleep(800);
>       cache.getIfPresent("1");
>       Assert.assertEquals(cache.size(), 2);
>       Thread.sleep(800);
>       cache.getIfPresent("1");
>       Assert.assertEquals(cache.size(), 2);
>       cache.cleanUp();
>       Assert.assertEquals(cache.size(), 1);
>   }
> ```

Clean it up every time will create Fury everytime, which is very expensive. Fury needs be cached.

**Comment by chaokunyang** [comment]
I see, thanks. Clean up it every time is not cheap for small objects.
image
image

Fury will replace guava cache with a fury implemented one, see more on #1113 . We can support clean up cache timely when access expired

**Comment by MrChang0** [comment]
fine, if we want remove guava dependency, we can try [caffeine](https://github.com/ben-manes/caffeine), maybe can shaded in fury.

**Comment by chaokunyang** [comment]
Yep, this is a smaller dependency. Fury is a low-level library, we want to make a zero-dependency in the long time. The cache usage in Fury is very simple. Maybe we can implement it manually too.

**Pull request merged**
