### PR TITLE
fix(Rust): incorrect cast

### PR DESCRIPTION
**Pull request by theweipeng**
1. Dismiss warnings
2. Fix incorrect type conversions which cause the failures in #1332

### CODE REVIEW

**Comment by theweipeng** [comment]
@LiangliangSui  Hi, I've fixed the test failures in this PR.

**Comment by LiangliangSui** [comment]
> @LiangliangSui Hi, I've fixed the test failures in this PR.

Thanks for fixing this problem. :+1:

**Comment by chaokunyang** [comment]
@LiangliangSui  With this PR merged, can we add windows CI in #1332 ?

**Comment by LiangliangSui** [comment]
> @LiangliangSui With this PR merged, can we add windows CI in #1332 ?

Of course, I have tested it locally and windows ci has passed.

Let’s merge this PR first.

**Review by chaokunyang — APPROVED** [review]
LGTM

**Pull request merged**
