### PR TITLE
feat(java): scoped meta share mode for type forward/backward compaibility

### PR DESCRIPTION
**Pull request by chaokunyang**
## What does this PR do?

This PR implements scoped meta share mode for type forward/backward compaibility

## Related issues

#202 

## Does this PR introduce any user-facing change?

- [ ] Does this PR introduce any public API change?
- [ ] Does this PR introduce any binary protocol compatibility change?

## Benchmark
Perf increased from `1900102.586` to `2430410.064`
```
Before:

Benchmark                                                       (bufferType)   (objectType)  (references)   Mode  Cnt        Score        Error  Units
fury_deserialize                              array  MEDIA_CONTENT         false  thrpt   10  2734151.212 ± 253921.628  ops/s
fury_deserialize_compatible                   array  MEDIA_CONTENT         false  thrpt   10  1900102.586 ±  62176.872  ops/s
furymetashared_deserialize_compatible         array  MEDIA_CONTENT         false  thrpt   10  3011439.327 ± 260518.752  ops/s

After:

Benchmark                                                       (bufferType)   (objectType)  (references)   Mode  Cnt        Score        Error  Units
fury_deserialize                              array  MEDIA_CONTENT         false  thrpt   10  2661186.814 ± 279377.198  ops/s
fury_deserialize_compatible                   array  MEDIA_CONTENT         false  thrpt   10  2430410.064 ± 164165.865  ops/s
furymetashared_deserialize_compatible         array  MEDIA_CONTENT         false  thrpt   10  3098083.064 ± 259391.053  ops/s
```

Size decreased from **732 to 577**:
```
Before
2024-05-30 01:00:49 INFO  FuryState:157 [fury_deserialize_compatible-jmh-worker-1] - ======> Fury | MEDIA_CONTENT | false | array | 732 |

After
2024-05-30 12:57:00 INFO  FuryState:157 [fury_deserialize_compatible-jmh-worker-1] - ======> Fury | MEDIA_CONTENT | false | array | 577 |
```

The

### CODE REVIEW

**Comment by chaokunyang** [comment]
Hi @MrChang0, this PR should make the meta share mode replace kv compatible mode for better performance and smaller space cost

**Review by theweipeng — APPROVED** [review]
LGTM

**Comment by MrChang0** [comment]
It fine for me, I will try to experiment this feature.
btw, how about increase that init buffer size in `org.apache.fury.meta.ClassDefEncoder#encodeClassDef`. take less growth operate may take more performance.

**Comment by chaokunyang** [comment]
> encodeClassDef

Would you like to submit a PR?

**Comment by chaokunyang** [comment]
Struct perf:
```
Before:
fury_deserialize                    array        STRUCT         false  thrpt   10  4103952.355 ± 461542.704  ops/s
fury_deserialize_compatible         array        STRUCT         false  thrpt   10  2104530.838 ± 283950.067  ops/s

After:
Benchmark                                             (bufferType)  (objectType)  (references)   Mode  Cnt        Score        Error  Units
fury_deserialize                    array        STRUCT         false  thrpt   10  3846945.672 ± 281139.320  ops/s
fury_deserialize_compatible         array        STRUCT         false  thrpt   10  3119394.319 ± 476422.038  ops/s
```

Size:
```
Before:
2024-05-30 02:06:42 INFO  FuryState:157 [fury_deserialize-jmh-worker-1] - ======> Fury | STRUCT | false | array | 710 |
2024-05-30 02:07:19 INFO  FuryState:157 [fury_deserialize_compatible-jmh-worker-1] - ======> Fury | STRUCT | false | array | 1134 |

After:
2024-05-30 02:01:16 INFO  FuryState:157 [fury_deserialize-jmh-worker-1] - ======> Fury | STRUCT | false | array | 710 |
2024-05-30 02:01:52 INFO  FuryState:157 [fury_deserialize_compatible-jmh-worker-1] - ======> Fury | STRUCT | false | array | 1227 |
```

Size bloat a little, we can optimize it later

**Pull request merged**
